using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp;
using Microsoft.CodeAnalysis.CSharp.Syntax;
using System.Collections.Immutable;
using System.Text;

namespace Generators;

[Generator]
public class DependencyPropertyGenerator : IIncrementalGenerator
{
    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        context.RegisterPostInitializationOutput(ctx => ctx.AddSource(
            "DependencyPropertyAttribute.g.cs",
            /* lang=C# */
            """
            using System;

            namespace DependencyPropertyGenerator;

            [System.Diagnostics.Conditional("COMPILE_TIME_ONLY")]
            [AttributeUsage(AttributeTargets.Property, AllowMultiple = false, Inherited = false)]
            internal class DependencyPropertyAttribute : Attribute
            {
            }
            """));

        var propertyDeclarations = context.SyntaxProvider.ForAttributeWithMetadataName(
            "DependencyPropertyGenerator.DependencyPropertyAttribute",
            (node, _) => IsPartialProperty(node),
            (context, _) => GetSemanticTargetForGeneration(context));

        var groupedProperties = propertyDeclarations
            .Collect()
            .Select((properties, _) => properties
                .GroupBy(p => (p.ClassName, p.Namespace))
                .Select(g => new ClassInfo(g.Key.ClassName, g.Key.Namespace, [.. g]))
                .ToImmutableArray());

        context.RegisterSourceOutput(groupedProperties, Execute);
    }

    private static bool IsPartialProperty(SyntaxNode node)
    {
        return node is PropertyDeclarationSyntax propertyDeclaration &&
               propertyDeclaration.Modifiers.Any(SyntaxKind.PartialKeyword);
    }

    private static PropertyInfo GetSemanticTargetForGeneration(GeneratorAttributeSyntaxContext context)
    {
        var p = (PropertyDeclarationSyntax)context.TargetNode;
        var t = context.SemanticModel.GetTypeInfo(p.Type).Type!;
        var ct = context.SemanticModel.GetDeclaredSymbol(p)!.ContainingType;

        var namespaceName = ct.ContainingNamespace.IsGlobalNamespace
            ? string.Empty
            : ct.ContainingNamespace.ToDisplayString();

        var pi = new PropertyInfo(
            p.Identifier.ValueText,
            GetCSharpTypeName(t),
            ct.Name,
            namespaceName);

        return pi;
    }

    private static string GetCSharpTypeName(ITypeSymbol typeSymbol)
    {
        return typeSymbol.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat.WithGlobalNamespaceStyle(SymbolDisplayGlobalNamespaceStyle.OmittedAsContaining));
    }

    private static void Execute(SourceProductionContext context, ImmutableArray<ClassInfo> classes)
    {
        foreach (var classInfo in classes)
        {
            var source = GenerateSource(classInfo);
            context.AddSource($"{classInfo.ClassName}.g.cs", source);
        }
    }

    private static string GenerateSource(ClassInfo classInfo)
    {
        var (className, namespaceName, properties) = classInfo;

        var namespaceDeclaration = string.IsNullOrEmpty(namespaceName)
            ? string.Empty
            : $"""
            namespace {namespaceName};


            """;

        var sb = new StringBuilder();

        foreach (var property in properties)
        {
            sb.Append($$"""
                public static readonly DependencyProperty {{property.PropertyName}}Property =
                    DependencyProperty.Register(
                        nameof({{property.PropertyName}}),
                        typeof({{property.PropertyType}}),
                        typeof({{className}}),
                        new PropertyMetadata(default({{property.PropertyType}})));

                public partial {{property.PropertyType}} {{property.PropertyName}}
                {
                    get => ({{property.PropertyType}})GetValue({{property.PropertyName}}Property);
                    set => SetValue({{property.PropertyName}}Property, value);
                }


            """);
        }

        var content = sb.ToString().TrimEnd();

        return $$"""
            // <auto-generated/>
            #nullable enable
            #pragma warning disable

            using System.Windows;

            {{namespaceDeclaration}}partial class {{className}}
            {
            {{content}}
            }
            """;
    }

    private record PropertyInfo(
        string PropertyName,
        string PropertyType,
        string ClassName,
        string Namespace);

    private record ClassInfo(
        string ClassName,
        string Namespace,
        ImmutableArray<PropertyInfo> Properties);
}
