using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp;
using Microsoft.CodeAnalysis.CSharp.Syntax;
using System.Collections.Immutable;
using System.Text;

namespace Generators;

[Generator]
public class NotifyPropertyChangedGenerator : IIncrementalGenerator
{
    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        context.RegisterPostInitializationOutput(ctx => ctx.AddSource(
            "NotifyPropertyChangedAttribute.g.cs",
            /* lang=C# */
            """
            using System;

            namespace NotifyPropertyChangedGenerator;

            [System.Diagnostics.Conditional("COMPILE_TIME_ONLY")]
            [AttributeUsage(AttributeTargets.Property, AllowMultiple = false, Inherited = false)]
            internal class NotifyPropertyChangedAttribute : Attribute
            {
            }
            """));

        var propertyDeclarations = context.SyntaxProvider.ForAttributeWithMetadataName(
            "NotifyPropertyChangedGenerator.NotifyPropertyChangedAttribute",
            (node, _) => IsPartialProperty(node),
            (context, _) => GetSemanticTargetForGeneration(context));

        var groupedProperties = propertyDeclarations
            .Collect()
            .Select((properties, _) => properties.GroupBy(p => (p.ClassName, p.Namespace))
            .Select(g => new ClassInfo(g.Key.ClassName, g.Key.Namespace, [.. g]))
            .ToImmutableArray());

        context.RegisterSourceOutput(groupedProperties, Execute);
    }

    private static bool IsPartialProperty(SyntaxNode node)
    {
        return node is PropertyDeclarationSyntax propertyDeclaration &&
               propertyDeclaration.Modifiers.Any(SyntaxKind.PartialKeyword);
    }

    private static PropertyInfo GetSemanticTargetForGeneration(GeneratorAttributeSyntaxContext context)
    {
        var p = (PropertyDeclarationSyntax)context.TargetNode;
        var t = context.SemanticModel.GetTypeInfo(p.Type).Type!;
        var ct = context.SemanticModel.GetDeclaredSymbol(p)!.ContainingType;

        var namespaceName = ct.ContainingNamespace.IsGlobalNamespace
            ? string.Empty
            : ct.ContainingNamespace.ToDisplayString();

        var pi = new PropertyInfo(
            p.Identifier.ValueText,
            GetCSharpTypeName(t),
            ct.Name,
            namespaceName);

        return pi;
    }

    private static string GetCSharpTypeName(ITypeSymbol typeSymbol)
    {
        return typeSymbol.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat.WithGlobalNamespaceStyle(SymbolDisplayGlobalNamespaceStyle.OmittedAsContaining));
    }

    private static void Execute(SourceProductionContext context, ImmutableArray<ClassInfo> classes)
    {
        foreach (var classInfo in classes)
        {
            var source = GenerateSource(classInfo);
            context.AddSource($"{classInfo.ClassName}.g.cs", source);
        }
    }

    private static string GenerateSource(ClassInfo classInfo)
    {
        var (className, namespaceName, properties) = classInfo;

        var namespaceDeclaration = string.IsNullOrEmpty(namespaceName)
            ? string.Empty
            : $"""
            namespace {namespaceName};


            """;

        var sb = new StringBuilder();

        foreach (var property in properties)
        {
            var eventArgsFieldName = $"{property.PropertyName}PropertyChangedEventArgs";

            sb.Append($$"""
                private static readonly PropertyChangedEventArgs {{eventArgsFieldName}} = new PropertyChangedEventArgs(nameof({{property.PropertyName}}));

                public partial {{property.PropertyType}} {{property.PropertyName}}
                {
                    get => field;
                    set => SetProperty(ref field, value, {{eventArgsFieldName}});
                }


            """);
        }

        return $$"""
            // <auto-generated/>
            #nullable enable
            #pragma warning disable

            using System.ComponentModel;

            {{namespaceDeclaration}}partial class {{className}} : INotifyPropertyChanged
            {
            {{sb}}    public event PropertyChangedEventHandler? PropertyChanged;

                protected virtual void OnPropertyChanged(PropertyChangedEventArgs e)
                {
                    PropertyChanged?.Invoke(this, e);
                }

                protected bool SetProperty<T>(ref T storage, T value, PropertyChangedEventArgs e)
                {
                    if (global::System.Collections.Generic.EqualityComparer<T>.Default.Equals(storage, value))
                    {
                        return false;
                    }
                    storage = value;
                    OnPropertyChanged(e);
                    return true;
                }
            }
            """;
    }

    private record PropertyInfo(
        string PropertyName,
        string PropertyType,
        string ClassName,
        string Namespace);

    private record ClassInfo(
        string ClassName,
        string Namespace,
        ImmutableArray<PropertyInfo> Properties);
}
