using Generators;
using Xunit;

namespace UnitTests;

public class Tests
{
    private const string Header = """
// <auto-generated/>
#nullable enable
#pragma warning disable

""";

    [Fact]
    public void SingleProperty()
    {
        Helpers.RunGenerator(
            new RecordEqualityGenerator(),
"""
namespace RecordEqualityGenerator;

partial record Person
{
    [ExplicitKey]
    public required string Name { get; init; }

    public int Id { get; init; }
    public int Age { get; init; }
}
""",
[
    new("RecordEqualityGenerator.Person.Equality", """
namespace RecordEqualityGenerator;

partial record Person
{
    public virtual bool Equals(Person? other)
    {
        return ReferenceEquals(this, other) || other is not null && EqualityContract == other.EqualityContract
            && global::System.Collections.Generic.EqualityComparer<string>.Default.Equals(Name, other.Name)
        ;
    }

    public override int GetHashCode()
    {
        var hash = new global::System.HashCode();
        hash.Add(EqualityContract);
        hash.Add(Name);
        return hash.ToHashCode();
    }
}
""")
],
null,
Header);
    }

    [Fact]
    public void MultipleProperties()
    {
        Helpers.RunGenerator(
            new RecordEqualityGenerator(),
"""
namespace RecordEqualityGenerator;

partial record Product
{
    [ExplicitKey]
    public int Id { get; init; }

    [ExplicitKey]
    public required string SKU { get; init; }

    public required string Name { get; init; }
    public decimal Price { get; init; }
}
""",
[
    new("RecordEqualityGenerator.Product.Equality", """
namespace RecordEqualityGenerator;

partial record Product
{
    public virtual bool Equals(Product? other)
    {
        return ReferenceEquals(this, other) || other is not null && EqualityContract == other.EqualityContract
            && global::System.Collections.Generic.EqualityComparer<int>.Default.Equals(Id, other.Id)
            && global::System.Collections.Generic.EqualityComparer<string>.Default.Equals(SKU, other.SKU)
        ;
    }

    public override int GetHashCode()
    {
        var hash = new global::System.HashCode();
        hash.Add(EqualityContract);
        hash.Add(Id);
        hash.Add(SKU);
        return hash.ToHashCode();
    }
}
""")
],
null,
Header);
    }

    [Fact]
    public void GenericRecord()
    {
        Helpers.RunGenerator(
            new RecordEqualityGenerator(),
"""
using RecordEqualityGenerator;

namespace Examples;

partial record Pair<T>(
    [property: ExplicitKey] T X,
    [property: ExplicitKey] string Y,
    string Other);
""",
[
    new("Examples.Pair`1.Equality", """
namespace Examples;

partial record Pair<T>
{
    public virtual bool Equals(Pair<T>? other)
    {
        return ReferenceEquals(this, other) || other is not null && EqualityContract == other.EqualityContract
            && global::System.Collections.Generic.EqualityComparer<T>.Default.Equals(X, other.X)
            && global::System.Collections.Generic.EqualityComparer<string>.Default.Equals(Y, other.Y)
        ;
    }

    public override int GetHashCode()
    {
        var hash = new global::System.HashCode();
        hash.Add(EqualityContract);
        hash.Add(X);
        hash.Add(Y);
        return hash.ToHashCode();
    }
}
""")
],
null,
Header);
    }

    [Fact]
    public void GenericRecordWithTwoTypeParameters()
    {
        Helpers.RunGenerator(
            new RecordEqualityGenerator(),
"""
using RecordEqualityGenerator;

namespace Examples;

partial record Pair<T1, T2>(
    [property: ExplicitKey] T1 X,
    [property: ExplicitKey] T2 Y,
    string Other);
""",
[
    new("Examples.Pair`2.Equality", """
namespace Examples;

partial record Pair<T1, T2>
{
    public virtual bool Equals(Pair<T1, T2>? other)
    {
        return ReferenceEquals(this, other) || other is not null && EqualityContract == other.EqualityContract
            && global::System.Collections.Generic.EqualityComparer<T1>.Default.Equals(X, other.X)
            && global::System.Collections.Generic.EqualityComparer<T2>.Default.Equals(Y, other.Y)
        ;
    }

    public override int GetHashCode()
    {
        var hash = new global::System.HashCode();
        hash.Add(EqualityContract);
        hash.Add(X);
        hash.Add(Y);
        return hash.ToHashCode();
    }
}
""")
],
null,
Header);
    }

    [Fact]
    public void GlobalNamespace()
    {
        Helpers.RunGenerator(
            new RecordEqualityGenerator(),
"""
using RecordEqualityGenerator;

partial record Item
{
    [ExplicitKey]
    public int Value { get; init; }
}
""",
[
    new("Item.Equality", """
partial record Item
{
    public virtual bool Equals(Item? other)
    {
        return ReferenceEquals(this, other) || other is not null && EqualityContract == other.EqualityContract
            && global::System.Collections.Generic.EqualityComparer<int>.Default.Equals(Value, other.Value)
        ;
    }

    public override int GetHashCode()
    {
        var hash = new global::System.HashCode();
        hash.Add(EqualityContract);
        hash.Add(Value);
        return hash.ToHashCode();
    }
}
""")
],
null,
Header);
    }

    [Fact]
    public void IgnoreKey_SingleProperty()
    {
        Helpers.RunGenerator(
            new RecordEqualityGenerator(),
"""
namespace RecordEqualityGenerator;

partial record Person
{
    public required string Name { get; init; }

    [IgnoreKey]
    public int Id { get; init; }

    [IgnoreKey]
    public int Age { get; init; }
}
""",
[
    new("RecordEqualityGenerator.Person.Equality", """
namespace RecordEqualityGenerator;

partial record Person
{
    public virtual bool Equals(Person? other)
    {
        return ReferenceEquals(this, other) || other is not null && EqualityContract == other.EqualityContract
            && global::System.Collections.Generic.EqualityComparer<string>.Default.Equals(Name, other.Name)
        ;
    }

    public override int GetHashCode()
    {
        var hash = new global::System.HashCode();
        hash.Add(EqualityContract);
        hash.Add(Name);
        return hash.ToHashCode();
    }
}
""")
],
null,
Header);
    }

    [Fact]
    public void IgnoreKey_MultipleProperties()
    {
        Helpers.RunGenerator(
            new RecordEqualityGenerator(),
"""
namespace RecordEqualityGenerator;

partial record Product
{
    public int Id { get; init; }

    public required string SKU { get; init; }

    [IgnoreKey]
    public required string Name { get; init; }

    [IgnoreKey]
    public decimal Price { get; init; }
}
""",
[
    new("RecordEqualityGenerator.Product.Equality", """
namespace RecordEqualityGenerator;

partial record Product
{
    public virtual bool Equals(Product? other)
    {
        return ReferenceEquals(this, other) || other is not null && EqualityContract == other.EqualityContract
            && global::System.Collections.Generic.EqualityComparer<int>.Default.Equals(Id, other.Id)
            && global::System.Collections.Generic.EqualityComparer<string>.Default.Equals(SKU, other.SKU)
        ;
    }

    public override int GetHashCode()
    {
        var hash = new global::System.HashCode();
        hash.Add(EqualityContract);
        hash.Add(Id);
        hash.Add(SKU);
        return hash.ToHashCode();
    }
}
""")
],
null,
Header);
    }
}
