using Generators;
using Xunit;

namespace UnitTests;

public class NotifyPropertyChangedGeneratorTests
{
    [Fact]
    public void Generate()
    {
        Helpers.RunGenerator(
            new NotifyPropertyChangedGenerator(),
            """
            using NotifyPropertyChangedGenerator;
            using INPC = NotifyPropertyChangedGenerator.NotifyPropertyChanged;

            class C
            {
                [NotifyPropertyChangedGenerator.NotifyPropertyChanged]
                public partial int Integer { get; set; }

                [NotifyPropertyChanged]
                public partial string? Str { get; set; }

                [NotifyPropertyChanged]
                public partial TimeOnly Time { get; set; }

                [NotifyPropertyChanged]
                public partial DateOnly? Date { get; set; }
            }
            """,
            [
                new("C", """
                // <auto-generated/>
                #nullable enable
                #pragma warning disable

                using System.ComponentModel;

                partial class C : INotifyPropertyChanged
                {
                    private static readonly PropertyChangedEventArgs IntegerPropertyChangedEventArgs = new PropertyChangedEventArgs(nameof(Integer));

                    private int _integer;

                    public partial int Integer
                    {
                        get => _integer;
                        set => SetProperty(ref _integer, value, IntegerPropertyChangedEventArgs);
                    }

                    private static readonly PropertyChangedEventArgs StrPropertyChangedEventArgs = new PropertyChangedEventArgs(nameof(Str));

                    private string _str;

                    public partial string Str
                    {
                        get => _str;
                        set => SetProperty(ref _str, value, StrPropertyChangedEventArgs);
                    }

                    private static readonly PropertyChangedEventArgs TimePropertyChangedEventArgs = new PropertyChangedEventArgs(nameof(Time));

                    private TimeOnly _time;

                    public partial TimeOnly Time
                    {
                        get => _time;
                        set => SetProperty(ref _time, value, TimePropertyChangedEventArgs);
                    }

                    private static readonly PropertyChangedEventArgs DatePropertyChangedEventArgs = new PropertyChangedEventArgs(nameof(Date));

                    private DateOnly? _date;

                    public partial DateOnly? Date
                    {
                        get => _date;
                        set => SetProperty(ref _date, value, DatePropertyChangedEventArgs);
                    }

                    public event PropertyChangedEventHandler? PropertyChanged;

                    protected virtual void OnPropertyChanged(PropertyChangedEventArgs e)
                    {
                        PropertyChanged?.Invoke(this, e);
                    }

                    protected bool SetProperty<T>(ref T storage, T value, PropertyChangedEventArgs e)
                    {
                        if (global::System.Collections.Generic.EqualityComparer<T>.Default.Equals(storage, value))
                        {
                            return false;
                        }
                        storage = value;
                        OnPropertyChanged(e);
                        return true;
                    }
                }
                """),
            ]);
    }
}
