using Generators;
using Xunit;

namespace UnitTests;

public class NotifyPropertyChangedGeneratorTests
{
    [Fact]
    public void Generate()
    {
        Helpers.RunGenerator(
            new NotifyPropertyChangedGenerator(),
            """
            using NotifyPropertyChangedGenerator;
            using INPC = NotifyPropertyChangedGenerator.NotifyPropertyChanged;

            class C
            {
                [NotifyPropertyChangedGenerator.NotifyPropertyChanged]
                public partial int Integer { get; set; }

                [NotifyPropertyChanged]
                public partial string? Str { get; set; }

                [NotifyPropertyChanged]
                public partial TimeOnly Time { get; set; }

                [NotifyPropertyChanged]
                public partial DateOnly? Date { get; set; }
            }
            """,
            [
                new("C", """
                // <auto-generated/>
                #nullable enable
                #pragma warning disable

                using System.ComponentModel;
                using System.Runtime.CompilerServices;

                partial class C : INotifyPropertyChanged
                {
                    private int _integer;

                    public partial int Integer
                    {
                        get => _integer;
                        set
                        {
                            if (!global::System.Collections.Generic.EqualityComparer<int>.Default.Equals(_integer, value))
                            {
                                _integer = value;
                                OnPropertyChanged();
                            }
                        }
                    }

                    private string _str;

                    public partial string Str
                    {
                        get => _str;
                        set
                        {
                            if (!global::System.Collections.Generic.EqualityComparer<string>.Default.Equals(_str, value))
                            {
                                _str = value;
                                OnPropertyChanged();
                            }
                        }
                    }

                    private TimeOnly _time;

                    public partial TimeOnly Time
                    {
                        get => _time;
                        set
                        {
                            if (!global::System.Collections.Generic.EqualityComparer<TimeOnly>.Default.Equals(_time, value))
                            {
                                _time = value;
                                OnPropertyChanged();
                            }
                        }
                    }

                    private DateOnly? _date;

                    public partial DateOnly? Date
                    {
                        get => _date;
                        set
                        {
                            if (!global::System.Collections.Generic.EqualityComparer<DateOnly?>.Default.Equals(_date, value))
                            {
                                _date = value;
                                OnPropertyChanged();
                            }
                        }
                    }

                    public event PropertyChangedEventHandler? PropertyChanged;

                    protected virtual void OnPropertyChanged([CallerMemberName] string? propertyName = null)
                    {
                        PropertyChanged?.Invoke(this, new PropertyChangedEventArgs(propertyName));
                    }
                }
                """),
            ]);
    }
}
